cd_workflowwwwsss

diff --git a/.github/workflows/cd-workflow.yml b/.github/workflows/cd-workflow.yml
--- a/.github/workflows/cd-workflow.yml
+++ b/.github/workflows/cd-workflow.yml
@@ -1,4 +1,3 @@
-# CD WORKFLOW
 name: Continuous Deployment
 
 on:
@@ -17,24 +16,22 @@ jobs:
 
       - name: Set up Minikube
         run: |
-          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
-          sudo install minikube-linux-amd64 /usr/local/bin/minikube
           minikube start
 
-      - name: Create MySQL deployment
+      - name: Create MySQL Deployment
         run: kubectl create -f ./resources/kubernetes/deployments/mysql.yaml
 
-      - name: Create phpMyAdmin deployment
-        run: kubectl create -f ./resources/kubernetes/deployments/phpmyadmn.yaml
+      - name: Create phpMyAdmin Deployment
+        run: kubectl create -f ./resources/kubernetes/deployments/phpmyadmin.yaml
 
-      - name: Create local deployment
+      - name: Create NGINX Service
+        run: kubectl create -f ./resources/kubernetes/services/local-service.yaml
+
+      - name: Create NGINX Deployment
         run: kubectl create -f ./resources/kubernetes/deployments/local-deployment.yaml
 
-      - name: Get Pods
-        run: kubectl get pods
-
-      - name: Get Services
-        run: kubectl get svc  # List all services to confirm
+      - name: List all Services
+        run: kubectl get svc
 
       - name: Get NGINX Service URL
         run: |
@@ -43,5 +40,5 @@ jobs:
 
       - name: Get phpMyAdmin Service URL
         run: |
-          PHPMYADMIN_URL=$(minikube service phpmyadmin --url || echo "Service not found")
-          echo "phpMyAdmin Service URL: $PHPMYADMIN_URL"
+          PMA_URL=$(minikube service phpmyadmin --url || echo "Service not found")
+          echo "phpMyAdmin Service URL: $PMA_URL"
